name: ./configure
description: Run ./configure for Darwin
inputs:
  configurationParameters:
    default: ''
    description: Additional flags for ./configure
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: php-src
      run: |
        set -x

        export PATH="/usr/local/opt/bison/bin:$PATH"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl@1.1/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/krb5/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libxml2/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libxslt/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/zlib/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/icu4c/lib/pkgconfig"

        ./buildconf --force
        ./configure \
          --prefix=/usr/local \
          --with-config-file-path=/etc \
          --with-config-file-scan-dir=/etc/php.d \
          --with-iconv=/usr/local/opt/libiconv \
          --enable-embed \
          --enable-zts \
          --disable-zend-signals \
          --enable-debug \
          ${{ inputs.configurationParameters }}
