name: Setup PHP
description: Setup PHP for Linux x32
inputs:
  version:
    description: PHP Version
    required: true
  configurationParameters:
    default: ''
    description: Additional flags for ./configure
    required: false
runs:
  using: composite
  steps:
    - name: Checkout PHP Source
      uses: ./.github/actions/php/checkout
      with:
        version: ${{ inputs.version }}

    - name: Setup Cache
      id: cache
      uses: ./.github/actions/php/cache
      with:
        os: linux-x32
        additionalKey: ${{ hashFiles('./.github/actions/php/linux-x32/configure/action.yml', './.github/actions/php/linux-x32/install/action.yml') }}

    - name: Install Packages
      uses: ./.github/actions/php/linux-x32/apt

    - name: Configure PHP
      if: steps.cache.outputs.cache-hit != 'true'
      uses: ./.github/actions/php/linux-x32/configure
      with:
        configurationParameters: ${{ inputs.configurationParameters }}

    - name: Install PHP
      uses: ./.github/actions/php/linux-x32/install
