name: Setup PHP
description: Setup PHP for Linux x64
inputs:
  version:
    description: PHP Version
    required: true
runs:
  using: composite
  steps:
    - name: Checkout PHP Source
      uses: ./.github/actions/php/checkout
      with:
        version: ${{ inputs.version }}

    - name: Setup Cache
      id: cache
      uses: ./.github/actions/php/cache
      with:
        os: linux-x64
        additionalKey: ${{ hashFiles('./.github/actions/php/linux-x64/configure/action.yml', './.github/actions/php/linux-x64/install/action.yml') }}

    - name: Install Packages
      uses: ./.github/actions/php/linux-x64/apt

    - name: Configure PHP
      if: steps.cache.outputs.cache-hit != 'true'
      uses: ./.github/actions/php/linux-x64/configure

    - name: Install PHP
      uses: ./.github/actions/php/linux-x64/install
