name: brew
description: Install Brew Packages
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        brew install \
          pkg-config \
          autoconf \
          bison \
          re2c
        brew install \
          bzip2 \
          enchant \
          libffi \
          intltool \
          libiconv \
          t1lib \
          libxml2 \
          libjpeg \
          libxslt
        brew link icu4c gettext --force
